/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTasksRouteImport } from './routes/api.tasks'
import { Route as ApiJournalRouteImport } from './routes/api.journal'
import { Route as ApiIntegrationsRouteImport } from './routes/api.integrations'
import { Route as ApiHabitsRouteImport } from './routes/api.habits'
import { Route as ApiFocusRouteImport } from './routes/api.focus'
import { Route as ApiFinanceRouteImport } from './routes/api.finance'
import { Route as ApiCyclesRouteImport } from './routes/api.cycles'
import { Route as ApiCheckoutRouteImport } from './routes/api.checkout'
import { Route as ApiBoardsRouteImport } from './routes/api.boards'
import { Route as ApiAuthRouteImport } from './routes/api.auth'
import { Route as ApiAffiliatesRouteImport } from './routes/api.affiliates'
import { Route as ApiAdminRouteImport } from './routes/api.admin'
import { Route as ApiWebhooksMercadopagoRouteImport } from './routes/api.webhooks.mercadopago'
import { Route as ApiCronLembretesRouteImport } from './routes/api.cron.lembretes'

const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJournalRoute = ApiJournalRouteImport.update({
  id: '/api/journal',
  path: '/api/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsRoute = ApiIntegrationsRouteImport.update({
  id: '/api/integrations',
  path: '/api/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHabitsRoute = ApiHabitsRouteImport.update({
  id: '/api/habits',
  path: '/api/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFocusRoute = ApiFocusRouteImport.update({
  id: '/api/focus',
  path: '/api/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinanceRoute = ApiFinanceRouteImport.update({
  id: '/api/finance',
  path: '/api/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCyclesRoute = ApiCyclesRouteImport.update({
  id: '/api/cycles',
  path: '/api/cycles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardsRoute = ApiBoardsRouteImport.update({
  id: '/api/boards',
  path: '/api/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAffiliatesRoute = ApiAffiliatesRouteImport.update({
  id: '/api/affiliates',
  path: '/api/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMercadopagoRoute = ApiWebhooksMercadopagoRouteImport.update({
  id: '/api/webhooks/mercadopago',
  path: '/api/webhooks/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronLembretesRoute = ApiCronLembretesRouteImport.update({
  id: '/api/cron/lembretes',
  path: '/api/cron/lembretes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/tutorial': typeof TutorialRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/affiliates': typeof ApiAffiliatesRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/boards': typeof ApiBoardsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/cycles': typeof ApiCyclesRoute
  '/api/finance': typeof ApiFinanceRoute
  '/api/focus': typeof ApiFocusRoute
  '/api/habits': typeof ApiHabitsRoute
  '/api/integrations': typeof ApiIntegrationsRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/tasks': typeof ApiTasksRoute
  '/api/cron/lembretes': typeof ApiCronLembretesRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/tutorial': typeof TutorialRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/affiliates': typeof ApiAffiliatesRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/boards': typeof ApiBoardsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/cycles': typeof ApiCyclesRoute
  '/api/finance': typeof ApiFinanceRoute
  '/api/focus': typeof ApiFocusRoute
  '/api/habits': typeof ApiHabitsRoute
  '/api/integrations': typeof ApiIntegrationsRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/tasks': typeof ApiTasksRoute
  '/api/cron/lembretes': typeof ApiCronLembretesRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/tutorial': typeof TutorialRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/affiliates': typeof ApiAffiliatesRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/boards': typeof ApiBoardsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/cycles': typeof ApiCyclesRoute
  '/api/finance': typeof ApiFinanceRoute
  '/api/focus': typeof ApiFocusRoute
  '/api/habits': typeof ApiHabitsRoute
  '/api/integrations': typeof ApiIntegrationsRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/tasks': typeof ApiTasksRoute
  '/api/cron/lembretes': typeof ApiCronLembretesRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/checkout'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/tutorial'
    | '/api/admin'
    | '/api/affiliates'
    | '/api/auth'
    | '/api/boards'
    | '/api/checkout'
    | '/api/cycles'
    | '/api/finance'
    | '/api/focus'
    | '/api/habits'
    | '/api/integrations'
    | '/api/journal'
    | '/api/tasks'
    | '/api/cron/lembretes'
    | '/api/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/checkout'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/tutorial'
    | '/api/admin'
    | '/api/affiliates'
    | '/api/auth'
    | '/api/boards'
    | '/api/checkout'
    | '/api/cycles'
    | '/api/finance'
    | '/api/focus'
    | '/api/habits'
    | '/api/integrations'
    | '/api/journal'
    | '/api/tasks'
    | '/api/cron/lembretes'
    | '/api/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/checkout'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/tutorial'
    | '/api/admin'
    | '/api/affiliates'
    | '/api/auth'
    | '/api/boards'
    | '/api/checkout'
    | '/api/cycles'
    | '/api/finance'
    | '/api/focus'
    | '/api/habits'
    | '/api/integrations'
    | '/api/journal'
    | '/api/tasks'
    | '/api/cron/lembretes'
    | '/api/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  TutorialRoute: typeof TutorialRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiAffiliatesRoute: typeof ApiAffiliatesRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiBoardsRoute: typeof ApiBoardsRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiCyclesRoute: typeof ApiCyclesRoute
  ApiFinanceRoute: typeof ApiFinanceRoute
  ApiFocusRoute: typeof ApiFocusRoute
  ApiHabitsRoute: typeof ApiHabitsRoute
  ApiIntegrationsRoute: typeof ApiIntegrationsRoute
  ApiJournalRoute: typeof ApiJournalRoute
  ApiTasksRoute: typeof ApiTasksRoute
  ApiCronLembretesRoute: typeof ApiCronLembretesRoute
  ApiWebhooksMercadopagoRoute: typeof ApiWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/journal': {
      id: '/api/journal'
      path: '/api/journal'
      fullPath: '/api/journal'
      preLoaderRoute: typeof ApiJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations': {
      id: '/api/integrations'
      path: '/api/integrations'
      fullPath: '/api/integrations'
      preLoaderRoute: typeof ApiIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/habits': {
      id: '/api/habits'
      path: '/api/habits'
      fullPath: '/api/habits'
      preLoaderRoute: typeof ApiHabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/focus': {
      id: '/api/focus'
      path: '/api/focus'
      fullPath: '/api/focus'
      preLoaderRoute: typeof ApiFocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance': {
      id: '/api/finance'
      path: '/api/finance'
      fullPath: '/api/finance'
      preLoaderRoute: typeof ApiFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cycles': {
      id: '/api/cycles'
      path: '/api/cycles'
      fullPath: '/api/cycles'
      preLoaderRoute: typeof ApiCyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boards': {
      id: '/api/boards'
      path: '/api/boards'
      fullPath: '/api/boards'
      preLoaderRoute: typeof ApiBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/affiliates': {
      id: '/api/affiliates'
      path: '/api/affiliates'
      fullPath: '/api/affiliates'
      preLoaderRoute: typeof ApiAffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mercadopago': {
      id: '/api/webhooks/mercadopago'
      path: '/api/webhooks/mercadopago'
      fullPath: '/api/webhooks/mercadopago'
      preLoaderRoute: typeof ApiWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/lembretes': {
      id: '/api/cron/lembretes'
      path: '/api/cron/lembretes'
      fullPath: '/api/cron/lembretes'
      preLoaderRoute: typeof ApiCronLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  TutorialRoute: TutorialRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiAffiliatesRoute: ApiAffiliatesRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiBoardsRoute: ApiBoardsRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiCyclesRoute: ApiCyclesRoute,
  ApiFinanceRoute: ApiFinanceRoute,
  ApiFocusRoute: ApiFocusRoute,
  ApiHabitsRoute: ApiHabitsRoute,
  ApiIntegrationsRoute: ApiIntegrationsRoute,
  ApiJournalRoute: ApiJournalRoute,
  ApiTasksRoute: ApiTasksRoute,
  ApiCronLembretesRoute: ApiCronLembretesRoute,
  ApiWebhooksMercadopagoRoute: ApiWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
