/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTasksRouteImport } from './routes/api.tasks'
import { Route as ApiJournalRouteImport } from './routes/api.journal'
import { Route as ApiIntegrationsRouteImport } from './routes/api.integrations'
import { Route as ApiHabitsRouteImport } from './routes/api.habits'
import { Route as ApiFocusRouteImport } from './routes/api.focus'
import { Route as ApiFinanceRouteImport } from './routes/api.finance'
import { Route as ApiCyclesRouteImport } from './routes/api.cycles'
import { Route as ApiAuthRouteImport } from './routes/api.auth'
import { Route as ApiAffiliatesRouteImport } from './routes/api.affiliates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJournalRoute = ApiJournalRouteImport.update({
  id: '/api/journal',
  path: '/api/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsRoute = ApiIntegrationsRouteImport.update({
  id: '/api/integrations',
  path: '/api/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHabitsRoute = ApiHabitsRouteImport.update({
  id: '/api/habits',
  path: '/api/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFocusRoute = ApiFocusRouteImport.update({
  id: '/api/focus',
  path: '/api/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinanceRoute = ApiFinanceRouteImport.update({
  id: '/api/finance',
  path: '/api/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCyclesRoute = ApiCyclesRouteImport.update({
  id: '/api/cycles',
  path: '/api/cycles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAffiliatesRoute = ApiAffiliatesRouteImport.update({
  id: '/api/affiliates',
  path: '/api/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/affiliates': typeof ApiAffiliatesRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/cycles': typeof ApiCyclesRoute
  '/api/finance': typeof ApiFinanceRoute
  '/api/focus': typeof ApiFocusRoute
  '/api/habits': typeof ApiHabitsRoute
  '/api/integrations': typeof ApiIntegrationsRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/tasks': typeof ApiTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/affiliates': typeof ApiAffiliatesRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/cycles': typeof ApiCyclesRoute
  '/api/finance': typeof ApiFinanceRoute
  '/api/focus': typeof ApiFocusRoute
  '/api/habits': typeof ApiHabitsRoute
  '/api/integrations': typeof ApiIntegrationsRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/tasks': typeof ApiTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/affiliates': typeof ApiAffiliatesRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/cycles': typeof ApiCyclesRoute
  '/api/finance': typeof ApiFinanceRoute
  '/api/focus': typeof ApiFocusRoute
  '/api/habits': typeof ApiHabitsRoute
  '/api/integrations': typeof ApiIntegrationsRoute
  '/api/journal': typeof ApiJournalRoute
  '/api/tasks': typeof ApiTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/affiliates'
    | '/api/auth'
    | '/api/cycles'
    | '/api/finance'
    | '/api/focus'
    | '/api/habits'
    | '/api/integrations'
    | '/api/journal'
    | '/api/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/affiliates'
    | '/api/auth'
    | '/api/cycles'
    | '/api/finance'
    | '/api/focus'
    | '/api/habits'
    | '/api/integrations'
    | '/api/journal'
    | '/api/tasks'
  id:
    | '__root__'
    | '/'
    | '/api/affiliates'
    | '/api/auth'
    | '/api/cycles'
    | '/api/finance'
    | '/api/focus'
    | '/api/habits'
    | '/api/integrations'
    | '/api/journal'
    | '/api/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAffiliatesRoute: typeof ApiAffiliatesRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiCyclesRoute: typeof ApiCyclesRoute
  ApiFinanceRoute: typeof ApiFinanceRoute
  ApiFocusRoute: typeof ApiFocusRoute
  ApiHabitsRoute: typeof ApiHabitsRoute
  ApiIntegrationsRoute: typeof ApiIntegrationsRoute
  ApiJournalRoute: typeof ApiJournalRoute
  ApiTasksRoute: typeof ApiTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/journal': {
      id: '/api/journal'
      path: '/api/journal'
      fullPath: '/api/journal'
      preLoaderRoute: typeof ApiJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations': {
      id: '/api/integrations'
      path: '/api/integrations'
      fullPath: '/api/integrations'
      preLoaderRoute: typeof ApiIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/habits': {
      id: '/api/habits'
      path: '/api/habits'
      fullPath: '/api/habits'
      preLoaderRoute: typeof ApiHabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/focus': {
      id: '/api/focus'
      path: '/api/focus'
      fullPath: '/api/focus'
      preLoaderRoute: typeof ApiFocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance': {
      id: '/api/finance'
      path: '/api/finance'
      fullPath: '/api/finance'
      preLoaderRoute: typeof ApiFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cycles': {
      id: '/api/cycles'
      path: '/api/cycles'
      fullPath: '/api/cycles'
      preLoaderRoute: typeof ApiCyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/affiliates': {
      id: '/api/affiliates'
      path: '/api/affiliates'
      fullPath: '/api/affiliates'
      preLoaderRoute: typeof ApiAffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAffiliatesRoute: ApiAffiliatesRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiCyclesRoute: ApiCyclesRoute,
  ApiFinanceRoute: ApiFinanceRoute,
  ApiFocusRoute: ApiFocusRoute,
  ApiHabitsRoute: ApiHabitsRoute,
  ApiIntegrationsRoute: ApiIntegrationsRoute,
  ApiJournalRoute: ApiJournalRoute,
  ApiTasksRoute: ApiTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
